### ISSUE TITLE
Invalid_argument error

### ISSUE THREAD

**Issue by sangeeta0201** [SaswatPadhi/PIE#12]
Hi Saswat,

For most of the test cases I get this error -
`
=== (12) List.combine(l0, l1) ===
Fatal error: exception Invalid_argument("Index past end of list")
`
Can it be fixed?

**Comment by SaswatPadhi** [comment]
Hi Sangeeta,

I just checked a fresh installation of PIE, I ran into some issues with both Python 2 and 3 being used within PIE -- I pushed a change that removed Python 2 dependence.

I suspect the issue you noticed could be related to this too. Could you try running `test_all.sh` again after `pip3 install --upgrade pyparsing`?

**Comment by sangeeta0201** [comment]
Hi Saswat. I have cloned PIE again and ran it using `test_all.sh` but I am still seeing same error -`=== (10) List.memq(m, l) ===
Fatal error: exception Invalid_argument("Index past end of list")
`
for most of the test cases.

**Comment by SaswatPadhi** [comment]
Hi Sangeeta,

Do you see something like this at the beginning?

```
 ############ CG_SIZE = 2 16 all ############

./test_all.sh: line 16: ../logs/$CGROUP/$FIX_TESTS/pie/$CG_SIZE/specs/list/RESULT: ambiguous redirect
Scanning line 513 ... DONE


=== (0) List.length(l) ===
    [%] Inferring {exception thrown} [k = 1] (0f x 6400t) ...
precondition: false
postcondition: exception thrown


real    0m0.176s
real    0m0.176s
user    0m0.160s
sys     0m0.011s
Scanning line 513 ... DONE


=== (0) List.length(l) ===
    [%] Removing conflicts ...  @2(15 explored)
    [%] Inferring {(res = 0)} [k = 1] (1f x 6400t) ...
precondition: (l = [])
postcondition: (res = 0)


real    0m0.241s
user    0m0.229s
sys     0m0.010s
Scanning line 513 ... DONE


=== (0) List.length(l) ===
Fatal error: exception Invalid_argument("Index past end of list")

real    0m0.008s
user    0m0.002s
sys     0m0.005s
Scanning line 513 ... DONE


=== (1) List.hd(l) ===
    [%] Removing conflicts ...  @2(15 explored)
    [%] Inferring {exception thrown} [k = 1] (1f x 6400t) ...
precondition: (l = [])
postcondition: exception thrown


real    0m0.234s
user    0m0.225s
sys     0m0.006s
Scanning line 513 ... DONE

.
.
.
```

If so, I suspect this is a non-issue :)
We have a list of postconditions for each function, and we iteratively infer preconditions on the arguments so the function meets the postcondition. The `Fatal_error` happens when we have checked all the postconditions in our list. I should silence it at some point, but right now it's just printed to screen.

For example, for `List.length` we check 2 postconditions above: `{exception thrown}` and `{(res = 0)}`, and then we exhaust the list of postconditions, so move on to the next function `List.hd`.

Let me know if you see something different when you run.

**Comment by sangeeta0201** [comment]
I see. Ya output looks same. I need to ask one more thing. What does false precondition mean? For this example below what is the precondition. 

```
=== (8) List.flatten(l) ===
    [%] Inferring {exception thrown} [k = 1] (0f x 6400t) ...                                     
precondition: false
postcondition: exception thrown


real	0m0.113s
user	0m0.104s
sys	0m0.008s
Scanning line 513 ... DONE


=== (8) List.flatten(l) ===
    [%] Removing conflicts ...  @2(15 explored)
    [%] Removing conflicts ...  @2 @3 @4 @5 @6 @7 @8 @9 @10 @11 @12 @13 @14 @15(71984 explored)
    [%] Inferring {res = []} [k = 7] (1f x 6400t) ...                                     
precondition: ~~ FAILED ~~
postcondition: res = []


real	0m4.803s
user	0m4.792s
sys	0m0.012s
Scanning line 513 ... DONE


=== (8) List.flatten(l) ===
Fatal error: exception Invalid_argument("Index past end of list")

real	0m0.003s
user	0m0.000s
sys	0m0.000s
Scanning line 513 ... DONE
```
Sorry to bother you so much. Thank you so much for helping me out.

**Comment by SaswatPadhi** [comment]
No problem at all. Glad it's running fine on your machine :)

`false` precondition indicates that the postcondition can never be
satisfied.
(Note that this is different from `-- FAILED --` which indicates PIE
couldn't find a precondition that's expressible in PIE's assumed grammar.)
